### ISSUE TITLE
Grabber?

### ISSUE THREAD

**Issue by FearLinux** [Rdimo/Discord-Injection#17]
Hello Rdimo, why is injection.js obfuscated? If it's open source, why obfuscate if any idiot can get the source? this is very strange.

**Comment by Rdimo** [comment]
> Hello Rdimo, why is injection.js obfuscated? If it's open source, why obfuscate if any idiot can get the source? this is very strange.

did you miss the whole fucking [Injection-clean.js?](https://github.com/Rdimo/Discord-Injection/blob/master/Injection-clean.js)
