### ISSUE TITLE
Dualhooked? No bitches? no open source?

### ISSUE THREAD

**Issue by Mani175** [Rdimo/Discord-Injection#19]
bro, it's Github, why do you obfuscate the code?
is that dualhooked?

**Comment by addi00000** [comment]
https://github.com/Rdimo/Discord-Injection/blob/master/Injection-clean.js

**Comment by GodFather227** [comment]
> bro, it's Github, why do you obfuscate the code?
> is that dualhooked?

Dumbass hoe join the server

**Comment by TheEpicGamers12** [comment]
> bro, it's Github, why do you obfuscate the code? is that dualhooked?

fat bitch are you fucking dumb do you suffer from a father figure nigga you are retarded as fuck no shit hazard v2 doesnt definetly have injection

**Comment by Rdimo** [comment]
> bro, it's Github, why do you obfuscate the code? is that dualhooked?

you blind?
