### ISSUE TITLE
What settings on obfuscator.io do i use i forgot uwu

### ISSUE THREAD

**Issue by LocalSmail** [Rdimo/Discord-Injection#5]
I'm a bad cotten picker ik :(

**Comment by addi00000** [comment]
0 cotton per second

**Comment by addi00000** [comment]
> my cps is as much as the cum in rdimos balls

Rdimo is a fem 😳

**Comment by Rdimo** [comment]
ill add a obfuscator.js file in the future so you can obfuscate it yourself
